name: Build

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby:
          - 2.7.6
          - 3.0.4
          - 3.1.2
          - 3.2.0-preview1
        rails:
          - "~> 6.0"
          - "~> 6.1"
          # - "~> 7.0" not yet supported due to sprockets/railties
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.7.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
      env:
        RAILS_VERSION: ${{ matrix.rails }}
    - name: Run tests
      run: bundle exec rake
      env:
        RAILS_VERSION: ${{ matrix.rails }}
        RUBY_VERSION: ${{ matrix.rails }}
    - name: Run linter
      run: bundle exec rubocop
      env:
        RAILS_VERSION: ${{ matrix.rails }}
        RUBY_VERSION: ${{ matrix.rails }}
