name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build-6-0:
    name: Rails 6.0
    uses: ./.github/workflows/rails.yml
    with:
      rails-version: "~> 6.0"

  build-6-1:
    name: Rails 6.1
    uses: ./.github/workflows/rails.yml
    with:
      rails-version: "~> 6.1"

  build-7-0:
    name: Rails 7.0
    uses: ./.github/workflows/rails.yml
    with:
      rails-version: "~> 7.0"
